### ISSUE TITLE
UAC disables sendkey during popup

### ISSUE THREAD

**Issue by hommmi** [MTK911/Attiny85#1]
I don't see how you bypassed UAC by just sending key to click yes to pop up when UAC dialog disables all such activity. Even system clock is not updated during popup and theme is changed so many functions are not allowed.
Please elaborate, thanks.

**Comment by MTK911** [comment]
I am unaware of such restriction provided with UAC pop-up which will stop HID attack. For argument sake please try this in your windows machine.

1. Press Win + R key
2. Type cmd
3. Press Ctrl + Shift + Return/Enter key
4. Wait for UAC pop-up and press Alt + y key

Following will select yes and that will execute cmd in admin mode. Showing how shortcut keys are being used during UAC pop-up in HID attack.
If you're mistaking HID attack with batch file execution than that is totally a different scenario and i am not using batch to send keys. 
Please let me know if i can be any more help.
