### ISSUE TITLE
Is it possible to use a less obvious phishing window? For example the Windows Security PopUp.

### ISSUE THREAD

**Issue by Zeymare** [MTK911/Attiny85#10]
I just want to say: Thank you for your work. The Phisher is absolutetly amazing and it does exactly what you expect it to do.

Now my Problem is that the window looks rather outdated. I mean people who arent so techsavy will believe it, but others not so much. So i wanted to ask if its possible to make a Window like this:

![112e975c-62f9-4bb0-97e6-2b8cbc7dcaa5](https://user-images.githubusercontent.com/59930176/111880900-3ca9ae00-89ae-11eb-992a-096d4bfbe76b.png)

A place where i saw it used is here for example:
https://github.com/Dviros/CredsLeaker
But this version obviously doesnt work on a digispark.

If its not possible, thats ok! Thanks in advance.

**Comment by MTK911** [comment]
Hi Zeymare,
If I remember correctly I tried to achieve this when I was coding current phishing script. I was unable to do so because size of code required to generate modern popup can't fit into Attiny85. So that is why it is not possible.
