### ISSUE TITLE
Unnecessary "" in Windows Phisher

### ISSUE THREAD

**Issue by msr8** [MTK911/Attiny85#12]
In line 13 of Windows_Phisher.ino, why is there `""` after `[ASDI]`? Even if we `""` those, the same keystrokes are given, so why is `""` there?

**Comment by MTK911** [comment]
When you're connected to a Domain in windows environment that "" allow you to get the domain name so they can be sent in login request for valid credentials checks.
I suppose you're checking it on environment which is not part of any domain that is why it is showing nothing.

Regards,
MTK
