### ISSUE TITLE
wifikey-grab sending passwords in encrypted format

### ISSUE THREAD

**Issue by Prateek-420** [MTK911/Attiny85#18]
The script runs fine but for some computers, it sends passwords in plaintext
![image](https://user-images.githubusercontent.com/80612728/141949213-0b34c336-8f17-4ca3-9ca8-dd70c883eb28.png)

But for some computers, it sends this. Can it be decrypted? and why is it happening
![image](https://user-images.githubusercontent.com/80612728/141948989-dad28f41-9f94-4e1b-b19b-6f1177f604e6.png)

**Comment by MTK911** [comment]
The encrypted passwords are result of encryption done on the machine and key for decryption is machine dependent meaning it can only be decrypted on machine which is storing the password.
