### ISSUE TITLE
cd %temp% do not exist

### ISSUE THREAD

**Issue by varefaz** [MTK911/Attiny85#2]
this is the error. 

PS: if you want in the italian keyboard to move the cmd the key is KEY_S not KEY_M

**Comment by MTK911** [comment]
Hey Varefaz,
Thanks for the suggestion on handling different (Italian) keyboard layout i have used the US layout as it's most used and default layout.
Regarding the error you are getting can you please share the name of payload you are getting this error in and also your setup where you are trying to run it; OS, Hardware, User type, Keyboard Layout etc so it would be very helpful in solving the problem.

Regards,
MTK

**Comment by varefaz** [comment]
OS: windows 10; Hardware: Asus; User: Admin; Keyboard Layout: italian
Payload: WifiKey-Grab_Minimize-of-Shame

**Comment by MTK911** [comment]
Thanks for the info. 
Please use following DigiKeyboard [library](https://github.com/Maiux92/digispark-keyboard-layout-italian
) for compiling your sketches and everything will work fine.
I have tested the mentioned library in following environment and have gotten the expected results.
**OS**: Windows 10
**Keyboard Layout**: Italian
**User Type:** Admin

saluti,
MTK

**Comment by varefaz** [comment]
Thank you very much.  I will try as soon as possible :)

**Comment by MTK911** [comment]
Happy to help :-)
