### ISSUE TITLE
INSTANT SHELL PROBLEM

### ISSUE THREAD

**Issue by ciro140903** [MTK911/Attiny85#25]
![image](https://user-images.githubusercontent.com/36792917/183977746-02676709-ae5a-4d34-b045-bc64437e2260.png)

**Comment by ciro140903** [comment]
why i'm getting this errors?

**Comment by ItsIgnacioPortal** [comment]
What even is that? What're you trying to do?

**Comment by ciro140903** [comment]
I'm trying to figure out why it doesn't work by copying and pasting pieces of code ...
in the screenshot there is the code present in the file "Instant_Shell.ino" line 27

**Comment by ciro140903** [comment]
because if I run the script as it is nothing happens ...

**Comment by ciro140903** [comment]
obviously on the other side, I'm listening with meterpreter

**Comment by ciro140903** [comment]
https://bytemeta.vip/repo/CedArctic/DigiSpark-Scripts/issues/43

my problem is the same

**Comment by MTK911** [comment]
It is probably because of the different language use try using English/en_us for the keyboard.
