### ISSUE TITLE
the key logger has virus on editing the file

### ISSUE THREAD

**Issue by NEWcodeBOoy** [MTK911/Attiny85#28]
<h2>Describe the bug</h2>

<br><br>
<h2>Check List</h2>

Before opening an Issue make sure following things are checked:
* [ ] Using English Keyboard 
* [ ] User have required privileges [e.g. is Admin, etc]
* [ ] webhook.site or anyother hook link is added in payload and link is working
<br><br>
<h2>Screenshots</h2>

<br><br>
<h2>Please complete the following information:</h2>

 - OS: [e.g. Win10, Win 7]
 - User Role/Group/Privilege [e.g. Administrator, User]
 - Keyboard layout & Language [e.g. QWERTY & English_US]
 - Change DigiKeyboard.print("powershell.... or DigiKeyboard.print("cmd.... to *DigiKeyboard.print("notepad");* and paste the notepad output here

**Comment by MTK911** [comment]
Yes, keyloggers are categorized as viruses. So antivirus will mark it as malicious.
