### ISSUE TITLE
Windows 11 task manager redesign

### ISSUE THREAD

**Issue by zallaevan** [MTK911/Attiny85#30]
<h2>Describe the bug</h2>

As I have stated in the comment, I think that line shall be changed in order to be useful with the new Windows 11 version and it's redesigned task manager. You can see said comment [here](https://github.com/MTK911/Attiny85/commit/5b421131f18e504edcedb9aa11b525ae1ffe52ce#r116085521).
<br><br>
<h2>Check List</h2>

Before opening an Issue make sure following things are checked:
* [x] Using English Keyboard 
* [x] User have required privileges [e.g. is Admin, etc]
* [x] webhook.site or anyother hook link is added in payload and link is working
<br><br>
<h2>Screenshots</h2>

<br><br>
<h2>Please complete the following information:</h2>

 - OS: W11
 - User Role/Group/Privilege User to Admin
 - Keyboard layout & Language QWERTY, Spanish (Int'l)
 - Change DigiKeyboard.print("powershell.... or DigiKeyboard.print("cmd.... to *DigiKeyboard.print("notepad");* and paste the notepad output here

**Comment by MTK911** [comment]
Thank you for the suggestion, I will have to make new payloads because of Windows 11 so I will look into this later.
