### ISSUE TITLE
Keylogger not outputting to webhook

### ISSUE THREAD

**Issue by GlorifyedToasterWithLegs** [MTK911/Attiny85#33]
basically just what the title says, I've made sure to check to see if the link is working with the wifi password grabber, and that works just fine, however, the keylogger code never ends up sending anything

**Comment by MTK911** [comment]
<a href="https://github.com/MTK911/Attiny85/issues/new/choose"><img src="https://i.ibb.co/W3z9Tjj/7ypmfy.jpg" alt="" border="0"></a>
