### ISSUE TITLE
Wifikey-Grab Dose not work for me

### ISSUE THREAD

**Issue by MrQuiet7** [MTK911/Attiny85#36]
its send a empty file
![Screenshot 2024-02-22 001424](https://github.com/MTK911/Attiny85/assets/136204820/a9772926-acbb-4606-a5b6-e8b564000857)

**Comment by MTK911** [comment]
![8gohvv](https://github.com/MTK911/Attiny85/assets/7070604/9244f6ee-52e6-4684-b02a-5d44a37ab9d5)
