### ISSUE TITLE
Only working by using "powershell"

### ISSUE THREAD

**Issue by Dasor** [MTK911/Attiny85#9]
So I have been trying the Windows Phisher and it works perfecly except in the line 

>  DigiKeyboard.println("powershell -noexit -command \"mode con cols=18 lines=1\"");

When I use the small poweshell when it goes to the main line (the one that does all the code) it just stops at the middle of the line and stops typing. But when I just do "powesell" it works just fine.

**Comment by MTK911** [comment]
Thanks for sharing your solution.
